name: Deploy Website to Kubernetes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build & Push Docker
      uses: docker/build-push-action@v6
      with:
        context: ./website_isw
        push: true
        tags: ghcr.io/pants/website-isw:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
